// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrpPB0aFdI-4wVQZyerv8LgPJA57-Mfo',
    appId: '1:142276423472:web:fa5dda993a305194fbe2f5',
    messagingSenderId: '142276423472',
    projectId: 'basic-restaurant-app',
    authDomain: 'basic-restaurant-app.firebaseapp.com',
    storageBucket: 'basic-restaurant-app.firebasestorage.app',
    measurementId: 'G-5M5NHGG8EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2djln0Bow4UtrJRKXrGtC13Ilau6ldmc',
    appId: '1:142276423472:android:eb7153ab032326fbfbe2f5',
    messagingSenderId: '142276423472',
    projectId: 'basic-restaurant-app',
    storageBucket: 'basic-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkJZBoVepnRUaEK4V-6Aw8HnA4SwFpvZg',
    appId: '1:142276423472:ios:1fabc2063d8472dafbe2f5',
    messagingSenderId: '142276423472',
    projectId: 'basic-restaurant-app',
    storageBucket: 'basic-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.basicRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkJZBoVepnRUaEK4V-6Aw8HnA4SwFpvZg',
    appId: '1:142276423472:ios:1fabc2063d8472dafbe2f5',
    messagingSenderId: '142276423472',
    projectId: 'basic-restaurant-app',
    storageBucket: 'basic-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.basicRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrpPB0aFdI-4wVQZyerv8LgPJA57-Mfo',
    appId: '1:142276423472:web:bb9e2ec43f9a4251fbe2f5',
    messagingSenderId: '142276423472',
    projectId: 'basic-restaurant-app',
    authDomain: 'basic-restaurant-app.firebaseapp.com',
    storageBucket: 'basic-restaurant-app.firebasestorage.app',
    measurementId: 'G-MEBVW352QT',
  );
}
